import path from "node:path";
import { mkdir, readFile, writeFile } from "node:fs/promises";

import { getSpacetimeDocsMarkdown } from "../context/spacetimeDocs.js";

export type ResourceInstallMode = "install" | "update";

interface ManagedResource {
  relativePath: string;
  content: string;
  kind: "markdown" | "json";
}

export interface InstallResourcesOptions {
  workspaceRoot: string;
  mode: ResourceInstallMode;
  version: string;
}

export interface ResourceSkip {
  path: string;
  reason: string;
}

export interface InstallResourcesResult {
  mode: ResourceInstallMode;
  workspaceRoot: string;
  created: string[];
  updated: string[];
  skipped: ResourceSkip[];
}

const MANAGED_MARKER = "spacetime-mcp-managed: true";

function withManagedMarkdown(body: string): string {
  return [
    `<!-- ${MANAGED_MARKER} -->`,
    "<!-- Generated by spacetime-mcp. Run `spacetime-mcp update` to refresh. -->",
    "",
    body.trim(),
    ""
  ].join("\n");
}

function getSkillMarkdown(): string {
  return withManagedMarkdown(`---
name: spacetimedb-development
description: Build and evolve SpacetimeDB reducers, tables, and client invocation flows.
---

# SpacetimeDB Development

## When to use this skill
Use this skill when implementing or modifying SpacetimeDB-backed domain features.

## Workflow

1. Read current schema and reducers using MCP tools.
2. Keep reducer names verb-driven and argument signatures explicit.
3. Update client invocation examples for TypeScript or Unity/C# when reducer contracts change.
4. Avoid generating REST routes or SQL migrations for reducer-first features.

## Quality Checklist

- Preserve table constraints and key fields.
- Validate reducer argument order with generated SDK bindings.
- Prefer additive schema evolution over breaking renames.
`);
}

function getGuidelineMarkdown(): string {
  return withManagedMarkdown(getSpacetimeDocsMarkdown());
}

function getMcpConfigJson(): string {
  return `${JSON.stringify(
    {
      "x-spacetime-mcp-managed": true,
      mcpServers: {
        "spacetime-mcp": {
          command: "npx",
          args: ["spacetime-mcp"]
        }
      }
    },
    null,
    2
  )}\n`;
}

function getSpacetimeConfigJson(version: string): string {
  return `${JSON.stringify(
    {
      "x-spacetime-mcp-managed": true,
      version,
      resources: {
        mcpConfig: ".mcp.json",
        guidelines: ".ai/guidelines/spacetimedb/core.md",
        skill: ".ai/skills/spacetimedb-development/SKILL.md"
      },
      commands: {
        install: "npx spacetime-mcp install",
        update: "npx spacetime-mcp update",
        mcp: "npx spacetime-mcp"
      }
    },
    null,
    2
  )}\n`;
}

function buildResources(version: string): ManagedResource[] {
  return [
    {
      relativePath: ".mcp.json",
      content: getMcpConfigJson(),
      kind: "json"
    },
    {
      relativePath: "spacetime-mcp.json",
      content: getSpacetimeConfigJson(version),
      kind: "json"
    },
    {
      relativePath: ".ai/guidelines/spacetimedb/core.md",
      content: getGuidelineMarkdown(),
      kind: "markdown"
    },
    {
      relativePath: ".ai/skills/spacetimedb-development/SKILL.md",
      content: getSkillMarkdown(),
      kind: "markdown"
    }
  ];
}

async function readIfExists(targetPath: string): Promise<string | undefined> {
  try {
    return await readFile(targetPath, "utf8");
  } catch {
    return undefined;
  }
}

function isManagedContent(kind: ManagedResource["kind"], existing: string): boolean {
  if (kind === "markdown") {
    return existing.includes(MANAGED_MARKER);
  }

  try {
    const parsed = JSON.parse(existing) as Record<string, unknown>;
    return parsed["x-spacetime-mcp-managed"] === true;
  } catch {
    return false;
  }
}

async function writeResourceFile(targetPath: string, content: string): Promise<void> {
  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, content, "utf8");
}

export async function installOrUpdateResources(
  options: InstallResourcesOptions
): Promise<InstallResourcesResult> {
  const resources = buildResources(options.version);
  const result: InstallResourcesResult = {
    mode: options.mode,
    workspaceRoot: options.workspaceRoot,
    created: [],
    updated: [],
    skipped: []
  };

  for (const resource of resources) {
    const absolutePath = path.join(options.workspaceRoot, resource.relativePath);
    const existing = await readIfExists(absolutePath);

    if (existing === undefined) {
      await writeResourceFile(absolutePath, resource.content);
      result.created.push(resource.relativePath);
      continue;
    }

    const managed = isManagedContent(resource.kind, existing);

    if (options.mode === "install") {
      if (!managed) {
        result.skipped.push({
          path: resource.relativePath,
          reason: "existing file is not managed by spacetime-mcp"
        });
        continue;
      }

      if (existing !== resource.content) {
        await writeResourceFile(absolutePath, resource.content);
        result.updated.push(resource.relativePath);
      }

      continue;
    }

    if (!managed) {
      result.skipped.push({
        path: resource.relativePath,
        reason: "existing file is not managed by spacetime-mcp"
      });
      continue;
    }

    if (existing !== resource.content) {
      await writeResourceFile(absolutePath, resource.content);
      result.updated.push(resource.relativePath);
    }
  }

  return result;
}
